//! Read/write the toolchain lock file (default
//! `android/toolchain.lock`, configurable via `agdk.toml`'s
//! `lockfile`). The lock carries the bundle's `release_tag`,
//! the pin snapshot it was packaged from, and the three asset
//! sha256s.
//!
//! Generated by `cargo agdk package` on the publish side; consumed
//! by `install`, `verify`, and `info` on the verify side.

use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::config::Config;
use crate::error::{Error, Result};
use crate::manifest::AssetKind;

const LOCK_HEADER: &str = "\
# Generated by `cargo agdk package`. Do not edit by hand.
#
# `release_tag` is content-addressed:
#     android-toolchain-agp{AGP}-ndk{NDK_MAJOR}-gradle{GRADLE}-{SHA8}
# where SHA8 = first 8 hex chars of
#     sha256(ndk_sha256 || sdk_sha256 || gradle_cache_sha256).
#
# `agp_version`, `ndk_version`, `gradle_version` are the pin snapshot
# this bundle was published for; `cargo agdk verify` cross-references
# them against the configured agp-file, ndk-file, and gradle-file at
# every run.
";

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct Lock {
    pub release_tag: String,
    pub agp_version: String,
    pub ndk_version: String,
    pub gradle_version: String,
    pub ndk_sha256: String,
    pub sdk_sha256: String,
    pub gradle_cache_sha256: String,
}

impl Lock {
    pub fn load(config: &Config) -> Result<Self> {
        Self::load_from(&config.abs(&config.lockfile))
    }

    pub fn load_from(path: &Path) -> Result<Self> {
        let text = std::fs::read_to_string(path)?;
        toml::from_str(&text).map_err(|e| Error::Parse {
            file: path.to_path_buf(),
            reason: e.to_string(),
        })
    }

    /// Serialize the lock with the canonical `LOCK_HEADER` banner
    /// prepended. `toml::to_string_pretty` doesn't emit comments, so
    /// the banner is owned here as a `const` rather than recovered
    /// from the on-disk file.
    pub fn save(&self, config: &Config) -> Result<()> {
        let path = config.abs(&config.lockfile);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let body = toml::to_string_pretty(self).expect("Lock serializes");
        std::fs::write(&path, format!("{LOCK_HEADER}\n{body}"))?;
        Ok(())
    }

    pub fn sha256_for(&self, kind: AssetKind) -> &str {
        match kind {
            AssetKind::Ndk => &self.ndk_sha256,
            AssetKind::Sdk => &self.sdk_sha256,
            AssetKind::GradleCache => &self.gradle_cache_sha256,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_TOML: &str = r#"# top comment

release_tag = "abc"
agp_version = "8.4.0"
ndk_version = "27.2.12479018"
gradle_version = "8.6"
ndk_sha256 = "ndk"
sdk_sha256 = "sdk"
gradle_cache_sha256 = "gc"
"#;

    fn fixture() -> Lock {
        Lock {
            release_tag: "abc".into(),
            agp_version: "8.4.0".into(),
            ndk_version: "27.2.12479018".into(),
            gradle_version: "8.6".into(),
            ndk_sha256: "ndk".into(),
            sdk_sha256: "sdk".into(),
            gradle_cache_sha256: "gc".into(),
        }
    }

    #[test]
    fn parses_lock_toml() {
        let parsed: Lock = toml::from_str(SAMPLE_TOML).unwrap();
        assert_eq!(parsed, fixture());
    }

    #[test]
    fn roundtrip_through_toml() {
        let body = toml::to_string_pretty(&fixture()).unwrap();
        let back: Lock = toml::from_str(&body).unwrap();
        assert_eq!(back, fixture());
    }

    #[test]
    fn sha256_for_dispatches() {
        let lock = fixture();
        assert_eq!(lock.sha256_for(AssetKind::Ndk), "ndk");
        assert_eq!(lock.sha256_for(AssetKind::Sdk), "sdk");
        assert_eq!(lock.sha256_for(AssetKind::GradleCache), "gc");
    }
}
